export const TYPES = {
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	GET_USER_GROUPS: 'GET_USER_GROUPS',
	FETCH_FROM_API: 'FETCH_FROM_API',
	CREATE_FROM_API: 'CREATE_FROM_API',
	UPDATE_CONTENT: 'UPDATE_CONTENT',
	RESET_CREATED: 'RESET_CREATED',
	UPDATE_SIDEBAR_VISIBILITY: 'UPDATE_SIDEBAR_VISIBILITY',
	SET_ACTIVITY_DATE: 'SET_ACTIVITY_DATE',
	SET_ACTIVITY_GROUP: 'SET_ACTIVITY_GROUP',
	RESET_ACTIVITY_GROUP: 'RESET_ACTIVITY_GROUP',
};
